apiVersion: apps/v1
kind: Deployment
metadata:
  name: "products-service-example"
  labels:
    app: "products-service-example"
    env: "stg"
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: "products-service-example"
      env: "stg"
  template:
    metadata:
      labels:
        app: "products-service-example"
        env: "stg"
    spec:
      nodeSelector:
        env: "stg"
      containers:
        - name: "products-service-example"
          image: "227416266472.dkr.ecr.us-east-1.amazonaws.com/products-service-example:latest-stg"
          imagePullPolicy: Always
          ports:
              - containerPort: 8081
                hostPort: 8081
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "products-service-example"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8081"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "120"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: "products-service-example"
    env: "stg"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
