apiVersion: apps/v1
kind: Deployment
metadata:
  name: "shipping-service-example"
  labels:
    app: "shipping-service-example"
    env: "stg"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "shipping-service-example"
  template:
    metadata:
      labels:
        app: "shipping-service-example"
    spec:
      nodeSelector:
        env: "stg"
      containers:
        - name: "shipping-service-example"
          image: "894577096821.dkr.ecr.us-east-1.amazonaws.com/shipping-service-example:latest-stg"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "shipping-service-example-service"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: "shipping-service-example"
    env: "stg"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080