apiVersion: apps/v1
kind: Deployment
metadata:
  name: "payments-service-example"
  labels:
    app: "payments-service-example"
    env: "dev"
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      env: "dev"
  template:
    metadata:
      labels:
        app: "payments-service-example"
        env: "dev"
    spec:
      nodeSelector:
        env: "dev"
      containers:
        - name: "payments-service-example"
          image: "894577096821.dkr.ecr.us-east-1.amazonaws.com/payments-service-example:latest-dev"
          imagePullPolicy: Always
          ports:
            - name: health-port
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: health-port
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: health-port
            initialDelaySeconds: 90
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "payments-service-example"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: "payments-service-example"
    env: "dev"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
